App/models/exercise.py
from App.database import db
class Exercise(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256), nullable=False)
    description = db.Column(db.String(5000))
    exercise_type = db.Column(db.String(256), nullable=False)  
    bodypart = db.Column(db.String(256), nullable=False)  
    equipment = db.Column(db.String(256), nullable=False)  
    level = db.Column(db.String(256), nullable=False)
    rating = db.Column(db.Float)  
    rating_desc = db.Column(db.String(256)) 

    def get_json(self):  
        return {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'exercises_type': self.type,
            'bodypart': self.bodypart,
            'equipment': self.equipment,
            'level': self.level,
            'rating': self.rating,
            'rating_desc': self.rating_desc
        }

App/models/user.py
from werkzeug.security import check_password_hash, generate_password_hash
from App.database import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username =  db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String(120), nullable=False)

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def get_json(self):
        return{
            'id': self.id,
            'username': self.username
        }

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password)
    
    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

App/controllers/user.py
from App.models import User
from App.models import Exercise
from App.models import UserRoutine
from App.database import db

def create_user(username, password):
    newuser = User(username=username, password=password)
    db.session.add(newuser)
    db.session.commit()
    return newuser

def get_user_by_username(username):
    return User.query.filter_by(username=username).first()

def get_user(id):
    return User.query.get(id)

def get_all_users():
    return User.query.all()

def get_all_users_json():
    users = User.query.all()
    if not users:
        return []
    users = [user.get_json() for user in users]
    return users

def update_user(id, username):
    user = get_user(id)
    if user:
        user.username = username
        db.session.add(user)
        return db.session.commit()
    return None

def get_all_exercises():
    return Exercise.query.all()

App/views/user.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required
from flask_jwt_extended import current_user, set_access_cookies

from.index import index_views
from App.models import Exercise, UserRoutine, db
from App.controllers import (
    create_user,
    get_all_users,
    get_all_users_json,
    jwt_required,
    login,
    get_user_by_username,
    get_all_exercises
)

user_views = Blueprint('user_views', __name__, template_folder='../templates')

@user_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users)

@user_views.route('/users', methods=['POST'])
def create_user_action():
    data = request.form
    flash(f"User {data['username']} created!")
    create_user(data['username'], data['password'])
    return redirect(url_for('user_views.get_user_page'))


@user_views.route('/api/users', methods=['GET'])
def get_users_action():
    users = get_all_users_json()
    return jsonify(users)

@user_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
    data = request.json
    user = create_user(data['username'], data['password'])
    return jsonify({'message': f"user {user.username} created with id {user.id}"})

@user_views.route('/static/users', methods=['GET'])
def static_user_page():
  return send_from_directory('static', 'static-user.html')




@user_views.route('/signup', methods=['GET'])
def get_signup_page():
    return render_template('signup.html')

@user_views.route('/signup', methods=['POST'])
def signup_user_action():
    data = request.form
    username = data['username']
    password = data['password']
    
    existing_user = get_user_by_username(username)
    if existing_user:
        flash('Username already taken')
        return redirect(url_for('user_views.get_signup_page'))

    create_user(username, password)
    flash('Account created!')

    token = login(username, password)

    if token:
        flash('Login Successful')
        response = redirect(url_for('index_views.get_index_page'))
        set_access_cookies(response, token)
        return response
    else:
        flash("Failed to log in after signup")
        return redirect(url_for('user_views.get_signup_page'))


@user_views.route('/exercises', methods=['GET'])
@user_views.route('/exercises/<int:exercise_id>', methods=['GET'])
@jwt_required()
def get_exercise_page(exercise_id=1):
    exercises = Exercise.query.all()
    user_routines = UserRoutine.get_user_routines(current_user.id)
    if exercise_id:
        selected_exercise=Exercise.query.filter_by(id=exercise_id).first()
    return render_template('exercises.html', exercises=exercises, selected_exercise=selected_exercise, user_routines=user_routines)

@user_views.route('/exercises/<int:selected_exercise_id>', methods=['POST'])
@jwt_required()
def add_exercise_to_routine(selected_exercise_id=None):
    routine_name = request.form.get('routine_name')

    if not routine_name or not selected_exercise_id:
        return jsonify({'error': 'Routine name or exercise ID not provided'}), 400

    user_id = current_user.id

    new_routine = UserRoutine(routine_name=routine_name, user_id=user_id, exercise_id=selected_exercise_id)
    db.session.add(new_routine)
    db.session.commit()
    flash("Exercise added to routine")
    return redirect(url_for('user_views.get_exercise_page'))


@user_views.route('/routines', methods=['GET'])
@user_views.route('/routines/<int:routine_id>', methods=['GET'])
@jwt_required()
def get_routines_page(routine_id=None):
    user_id = current_user.id
    user_routines = UserRoutine.get_user_routines(user_id)

    if routine_id is not None:
        selected_routine = UserRoutine.query.get(routine_id)
        if selected_routine and selected_routine.user_id == current_user.id:
            exercises = selected_routine.get_exercises()
            return render_template('routines.html', user_routines=user_routines, selected_routine=selected_routine, exercises=exercises)
        else:
            flash('You do not have permission to view this routine.', 'error')
            return redirect(url_for('user_views.get_routines_page'))
    else:
        return render_template('routines.html', user_routines=user_routines)

@user_views.route('/routines', methods=['POST'])
@jwt_required()
def create_routine():
    user_id = current_user.id
    routine_name = request.form.get('routine-name')

    if not routine_name:
        flash('Routine name cannot be empty.', 'error')
        return redirect(url_for('user_views.get_routines_page'))

    existing_routine = UserRoutine.query.filter_by(user_id=user_id, routine_name=routine_name).first()
    if existing_routine:
        flash('Routine name already exists. Please choose a different name.', 'error')
        return redirect(url_for('user_views.get_routines_page'))

    new_routine = UserRoutine(routine_name=routine_name, user_id=user_id)
    db.session.add(new_routine)
    db.session.commit()
    flash('New routine created successfully!', 'success')
    return redirect(url_for('user_views.get_routines_page'))


@user_views.route('/routines/<int:routine_id>/exercises/<int:exercise_id>', methods=['POST'])
@jwt_required()
def delete_exercise_from_routine(routine_id, exercise_id):
    user_id = current_user.id

    selected_routine = UserRoutine.query.filter_by(id=routine_id).first()
    if selected_routine:
        routine_name = selected_routine.routine_name
    else:
        flash('Routine not found', 'error')
        return redirect(url_for('user_views.get_routines_page'))
    
    user_routine = UserRoutine.query.filter_by(user_id=user_id, routine_name=routine_name, exercise_id=exercise_id).first()
    if user_routine:
        db.session.delete(user_routine)
        db.session.commit()
        flash('Exercise removed from routine successfully', 'success')
    else:
        flash('Exercise not found in the selected routine', 'error')
    
    return redirect(url_for('user_views.get_routines_page'))


@user_views.route('/routines/<int:routine_id>', methods=['POST'])
@jwt_required()
def delete_routine(routine_id):
    user_id = current_user.id
    selected_routine = UserRoutine.query.filter_by(id=routine_id).first()

    if selected_routine:
        routine_name = selected_routine.routine_name
    else:
        flash('Routine not found', 'error')
        return redirect(url_for('user_views.get_routines_page'))

    user_routines = UserRoutine.query.filter_by(user_id=user_id, routine_name=routine_name).all()
    if user_routines:
        for user_routine in user_routines:
            db.session.delete(user_routine)
        db.session.commit()
        flash('Routine deleted successfully', 'success')
    else:
        flash('Routine not found', 'error')
    
    return redirect(url_for('user_views.get_routines_page'))

App/templates/401.html
{% extends "layout.html" %}
{% block title %}Not Authorized{% endblock %}
{% block page %}Not Auhtorized{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <div class="card-content">
                <h1>401 - Not Authorized</h1>
                <p>You do not have permission to access this resource. Please check your credentials and try again.</p>
                <p>{{error}}</p>
            </div>
            <div class="card-action">
                <a href="/" class="waves-effect waves-light btn">Go Home</a>
                <a href="javascript:history.back()" class="waves-effect waves-light btn">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/exercises.html
{% extends "layout.html" %}
{% block title %}WORKOUT PLANNER{% endblock %}
{% block page %}WORKOUT PLANNER{% endblock %}

{% block styles %}
<style>
    .collection .collection-item.active{
        background-color: cornflowerblue;
    }

    .list-container {
        border: 2px solid #ccc;
        border-radius: 5px;
        max-height: 200px;
        overflow-y: scroll;
        padding: 20px;
    }

    .heading {
        text-align: center;
    }

</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col m5">
        <div class="heading"><h5>EXERCISES</h5></div>
        <div class="list-container collection" style="max-height: 78vh; overflow-y: scroll; margin-left: 10px;">
                {% for exercise in exercises %}
                    {% if selected_exercise and exercise.id==selected_exercise.id %}
                        <a id="{{exercise.id}}" href="/exercises/{{exercise.id}}" class="collection-item active white-text">{{exercise.title}}</a>
                    {% else %}
                        <a id="{{exercise.id}}" href="/exercises/{{exercise.id}}" class="collection-item black-text">{{exercise.title}}</a>
                    {% endif %}
                {% endfor %}
        </div>
    </div>
    
    <div class="col m7">
        <div class="heading"><h5>INFORMATION</h5></div>
        <div>
            <h5 style="text-align: center;">{{selected_exercise.title}}</h5>
            <h5>Description</h5>
            <p>{{selected_exercise.description}}</p>
            <h5>Type</h5>
            <p>B{{selected_exercise.exercise_type}}</p>
            <h5>Body Part</h5>
            <p>{{selected_exercise.bodypart}}</p>
            <h5>Equipment</h5>
            <p>{{selected_exercise.equipment}}</p>
            <h5>Level</h5>
            <p>{{selected_exercise.level}}</p>

            <form id="add-exercise-form" action="/exercises/{{selected_exercise.id}}" method="POST">
                <div class="input-field col s9">
                    <select id="routine-select" name="routine_name">
                        <option value="" disabled selected>Choose routine</option>
                        {% for routine in user_routines %}
                            <option value="{{ routine.routine_name }}">{{ routine.routine_name }}</option>
                        {% endfor %}
                    </select>
                    <label>Select Routine</label>
                </div>
                <input type="hidden" id="exercise-id" name="exercise_id">
                <div class="col s12">
                    <button class="btn waves-effect waves-light" type="submit">Add to Routine</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

App/templates/index.html
{% extends "layout.html" %}
{% block title %}Workout Planner{% endblock %}
{% block page %}Workout Planner{% endblock %}

{{ super() }}

{% block content %}
    
    {% if is_authenticated %}
        <p> Welcome {{current_user.username}} </p>
    {% endif %}
    
{% endblock %}

App/templates/layout.html
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
     <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
  </head>
  <body>
    
      <nav class="blue">
          <div class="nav-wrapper">
              <a href="/index" class="brand-logo center">{% block page %}{% endblock %}</a>
              
              {% if is_authenticated %}
              <ul id="nav-mobile" class="left">
                  <li><a href="/exercises">Exercises</a></li>
                  <li><a href="/routines">Routines</a></li>
              </ul>
              <ul id="nav-mobile" class="right">
                <li><a href="/logout">Logout</a></li>
              </ul>
              {% else %}

              {% endif %}
              
          </div>
      </nav>
      <style>
          .navbar-form label {
              color: white !important;
          }
      </style>

    <div  id="content">{% block content %}{% endblock %}</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
       M.AutoInit();

        {% with messages = get_flashed_messages() %}
          {% if messages %}
              {% for message in messages %}
              M.toast({html: '{{message}}'})
              {% endfor %}
          {% endif %}
        {% endwith %}
       
    </script>
  </body>
</html>

App/templates/login.html
{% extends "layout.html" %}
{% block title %}Workout Planner{% endblock %}
{% block page %}Workout Planner{% endblock %}

{{ super() }}

{% block styles %}
  <style>
  body {
    background-image: url("https://img.freepik.com/free-photo/top-view-perfectly-ordered-fitness-items_23-2150321808.jpg");
    background-size: cover;
    background-position: center;
    min-height: 100vh;
  }

  .wrapper {
    width: 420px;
    background: rgba(0, 0, 0, 0.5);
    border: 2px solid rgba(255, 255, 255, .2);
    border-radius: 12px;
    padding: 30px 40px;
    margin: 100px auto;
}

.wrapper h1 {
    font-size: 24px;
    margin-bottom: 30px;
    text-align: center;
    color: #fff;
    margin-top: 30px;
}

.input-box label {
    font-size: 15px;
}

.input-box {
    position: relative;
    width: 100%;
    height: 50px;
    margin-bottom: 30px;
}

.input-box input {
    width: 100%;
    height: 100%;
    background: transparent;
    border: none;
    outline: none;
    border: 2px solid rgba(255, 255, 255, .2);
    border-radius: 40px;
    font-size: 16px;
    color: #fff;
    padding: 20px 20px 20px 20px;
}

.input-box input::placeholder {
    color: #fff;
}

.input-box i {
    position: absolute;
    right: 20px;
    top: 50%;
    transform: translateY(-50%);
    font-size: 20px;
    color:#fff
}

.btn {
    width: 100%;
    height: 45px;
    background: #fff;
    border: none;
    outline: none;
    border-radius: 40px;
    box-shadow: 0 0 10px rgba(0, 0, 0, .1);
    cursor: pointer;
    font-size: 16px;
    color: #333;
    font-weight: 600;
}

.register-link {
    font-size: 14.5px;
    text-align: center;
    margin-top: 20px;
}

.register-link p a {
    color: #ffffff;
    text-decoration: none;
    font-weight: 600;
}

.register-link p {
    color: #fff;
}
  </style>
{% endblock %}

{% block content %}
    <div class="wrapper">
        <form method="POST" action="/login">
          <h1>Login</h1>
          <div class="input-box">
            <input type="text" placeholder="Username" class="validate"name="username" required>
            <i class="material-icons">account_circle</i>
          </div>
          <div class="input-box">
            <input type="password" class="validate" placeholder="Password" name="password" required>
            <i class="material-icons">lock</i>
          </div>
          <button type="submit" class="btn">Login</button>
          <div class="register-link">
            <p>Dont have an account? </p>
            <a href="/signup" class="btn"> Sign Up</a>
          </div>
        </form>
      </div>
{% endblock %}

App/templates/message.html
{% extends "layout.html" %}
{% block title %}{{title}}{% endblock %}
{% block page %}{{title}}{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <p>{{message}}</p>
        </div>
    </div>
</div>
{% endblock %}

App/templates/routines.html
{% extends "layout.html" %}
{% block title %}WORKOUT PLANNER{% endblock %}
{% block page %}WORKOUT PLANNER{% endblock %}

{% block styles %}
<style>
    .collection .collection-item.active {
        background-color: cornflowerblue;
    }

    .list-container {
        border: 2px solid #ccc;
        border-radius: 5px;
        max-height: 200px;
        overflow-y: scroll;
        padding: 20px;
    }

    .heading {
        text-align: center;
    }

    .create-routine-container {
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 20px;
    }

    .create-routine-container form {
        margin-right: 10px;
    }

    .routine-heading {
        margin-left: 30px;
    }

    .create-routine-container button {
    margin-top: 10px;
}

</style>
{% endblock %}

{% block content %}
<div class="row" style="margin-bottom: 0px;">
    <div class="col s12">
        <div class="create-routine-container">
            <h5 class="routine-heading">Welcome {{current_user.username}}</h5>
            <h5 class="routine-heading">Create Routine?</h5>
            <form id="create-routine-form" class="col s10" method="POST" action="{{ url_for('user_views.create_routine') }}">
                <div class="input-field col s10">
                    <input id="routine-name" name="routine-name" type="text" class="validate">
                    <label for="routine-name">Routine Name</label>
                </div>
                <button class="btn waves-effect waves-light" type="submit" name="action">Create
                <i class="material-icons right">add</i>
                </button>
            </form>
            
        </div>
    </div>
</div>
<div class="row" style="margin-bottom: 0px;">
    <div class="col m5">
        <div class="heading"><h5>Your Routines</h5></div>
        <div class="list-container collection" style="max-height: 65vh; overflow-y: scroll; margin-left: 10px;">
            {% for routine in user_routines %}
                {% if selected_routine and routine.id == selected_routine.id %}
                    <a id="{{routine.id}}" href="/routines/{{routine.id}}" class="collection-item active white-text">{{ routine.routine_name }}
                        <form style="display: inline;" action="{{ url_for('user_views.delete_routine', routine_id=routine.id) }}" method="POST">
                            <button class="btn-flat waves-effect waves-light" type="submit">
                                <i class="material-icons right" style="justify-content: space-between;">delete_forever</i>
                            </button>
                        </form>
                    </a>
                {% else %}
                    <a id="{{routine.id}}" href="/routines/{{routine.id}}" class="collection-item black-text">{{ routine.routine_name }}
                        <form style="display: inline;" action="{{ url_for('user_views.delete_routine', routine_id=routine.id) }}" method="POST">
                            <button class="btn-flat waves-effect waves-light" type="submit">
                                <i class="material-icons right" style="justify-content: space-between;">delete_forever</i>
                            </button>
                        </form>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    
    <div class="col m7">
        <div class="heading" style="text-align: center;"><h5>Exercises</h5></div>
        <div class="list-container collection" style="max-height: 65vh; overflow-y: scroll; margin-left: 10px;">
            <ul class="collapsible">
                {% if exercises %}
                    {% for exercise in exercises %}
                        <li>
                            <div class="collapsible-header">{{exercise.title}}</div>
                            <div class="collapsible-body">
                                <span><h6>Description</h6>
                                    <p>{{exercise.description}}</p>
                                    <h6>Type</h6>
                                    <p>B{{exercise.exercise_type}}</p>
                                    <h6>Body Part</h6>
                                    <p>{{exercise.bodypart}}</p>
                                    <h6>Equipment</h6>
                                    <p>{{exercise.equipment}}</p>
                                    <h6>Level</h6>
                                    <p>{{exercise.level}}</p>
                                    <form action="{{ url_for('user_views.delete_exercise_from_routine', routine_id=selected_routine.id, exercise_id=exercise.id) }}" method="POST">
                                        <button class="btn waves-effect waves-light" type="submit" name="action">Remove
                                            <i class="material-icons right">remove_circle</i>
                                        </button>
                                    </form>
                                </span>
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <p style="text-align: center;">No Routine Selected Or Exercises Not Found In Routine.</p>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(elems);
    });

    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.modal');
        var instances = M.Modal.init(elems);
    });

    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.tooltipped');
        var instances = M.Tooltip.init(elems);
    });
</script>
{% endblock %}

App/templates/signup.html
{% extends "layout.html" %}
{% block title %}Workout Planner{% endblock %}
{% block page %}Workout Planner{% endblock %}

{{ super() }}

{% block styles %}
  <style>
  body {
    background-image: url("https://img.freepik.com/free-photo/top-view-perfectly-ordered-fitness-items_23-2150321808.jpg");
    background-size: cover;
    background-position: center;
    min-height: 100vh;
  }

  .wrapper {
    width: 420px;
    background: rgba(0, 0, 0, 0.5);
    border: 2px solid rgba(255, 255, 255, .2);
    border-radius: 12px;
    padding: 30px 40px;
    margin: 100px auto;
}

.wrapper h1 {
    font-size: 24px;
    margin-bottom: 30px;
    text-align: center;
    color: #fff;
    margin-top: 30px;
}

.input-box label {
    font-size: 15px;
}

.input-box {
    position: relative;
    width: 100%;
    height: 50px;
    margin-bottom: 30px;
}

.input-box input {
    width: 100%;
    height: 100%;
    background: transparent;
    border: none;
    outline: none;
    border: 2px solid rgba(255, 255, 255, .2);
    border-radius: 40px;
    font-size: 16px;
    color: #fff;
    padding: 20px 20px 20px 20px;
}

.input-box input::placeholder {
    color: #fff;
}

.input-box i {
    position: absolute;
    right: 20px;
    top: 50%;
    transform: translateY(-50%);
    font-size: 20px;
    color:#fff
}

.btn {
    width: 100%;
    height: 45px;
    background: #fff;
    border: none;
    outline: none;
    border-radius: 40px;
    box-shadow: 0 0 10px rgba(0, 0, 0, .1);
    cursor: pointer;
    font-size: 16px;
    color: #333;
    font-weight: 600;
}

.register-link {
    font-size: 14.5px;
    text-align: center;
    margin-top: 20px;
}

.register-link p a {
    color: #ffffff;
    text-decoration: none;
    font-weight: 600;
}

.register-link p {
    color: #fff;
}

  </style>
{% endblock %}

{% block content %}
    <div class="wrapper">
        <form method="POST" action="/signup">
          <h1>Sign Up</h1>
          <div class="input-box">
            <input type="text" placeholder="Username" class="validate" name="username" required>
            <i class="material-icons">account_circle</i>
          </div>
          <div class="input-box">
            <input type="password" class="validate" placeholder="Password" name="password" required>
            <i class="material-icons">lock</i>
          </div>
          <button type="submit" class="btn">Sign Up</button>
          <div class="register-link">
            <p>Already have an account? </p>
            <a href="/" class="btn"> Login</a>
          </div>
        </form>
      </div>
{% endblock %}

App/templates/users.html
{% extends "layout.html" %}
{% block title %}App Users{% endblock %}
{% block page %}App Users{% endblock %}

{{ super() }}

{% block content %}
    <div class="row">
        <p>
            This is table is renderd on the Server. Flask gets the data from the database and uses jinja templates to dyanmically render this page when a request is sent to <a href="/users">/users</a>.
        </p>
    </div>

    <div class="row">
      <form class="col s12" method="POST" action="/users">
        
        <div class="row">
          <div class="input-field col s6">
            <input placeholder="Username" name="username" type="text" class="validate">
            <label for="username">Username</label>
          </div>
          <div class="input-field col s6">
            <input placeholder="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
      
        <div class="row">
          <div class="input-field col s12">
            <button class="btn waves-effect waves-light right purple" type="submit" name="action">Submit</button>
          </div>
        </div> 

      </form>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Id</th><th>Username</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>

{% endblock %}